language: ruby
branches:
  only:
    - master
matrix:
  include:
    # See https://docs.travis-ci.com/user/reference/osx/
    - os: osx
      osx_image: xcode12
      # macOS 10.15
    - os: osx
      osx_image: xcode11
      # macOS 10.14
install:
  - brew update
  - brew install xquartz
  - brew install svg2png
script:
  - make
  - make install
  - open /Applications/AzPainter.app
  - sleep 10
  - pgrep azpainter
  - pkill azpainter
